name: Publish release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: read

jobs:
  publish-to-pypi:
    if: ${{ github.event.workflow_run.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/omikuji2/
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          pattern: python-*
          path: dist/
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
